apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /home/nfs/elasticsearch1
    server: 192.168.10.159
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /home/nfs/elasticsearch2
    server: 192.168.10.159
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv3
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /home/nfs/elasticsearch3
    server: 192.168.10.159
